name: Drizzle DB Generate & Push

on:
  push:
    branches:
      - main

jobs:
  db-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Generate migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx drizzle-kit generate

      - name: Push migrations to Neon
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx drizzle-kit migrate
